import "~/styles/globals.css";

import { Inconsolata } from "next/font/google";
import { headers } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import { ThemeProvider } from "./_components/theme-toggle/theme-provider";

const inconsolata = Inconsolata({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "GraphQuest",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`font-sans ${inconsolata.variable}`}
        suppressHydrationWarning={true}
      >
        <TRPCReactProvider headers={headers()}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark" //TODO: "system" working on lightmode
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
