import "~/styles/globals.css";

import { Inconsolata } from "next/font/google";
import { headers } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";

const inconsolata = Inconsolata({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "GraphQuest",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`font-sans ${inconsolata.variable}`}
        suppressHydrationWarning={true}
      >
        <TRPCReactProvider headers={headers()}>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
